### ISSUE TITLE
ems does not have model.py

### ISSUE THREAD

**Issue by dingquanyu** [allanchen95/ESMPair#6]
Hi,

There is no model.py file under the ems folder after  installing fair-esm.  How do we replace the esm/model.py in the directory of site-packages/ with the provided model.py ?

**Comment by allanchen95** [comment]
Hi, as ESM had updated their model implementations, our codes are out-of-date. We just updated the new implementation of ESMPair, "You need to replace the esm/model/msa_transformer.py in the directory of {your python path}/site-packages/ with the provided msa_transformer.py. In the new msa_transformer.py".

**Comment by dingquanyu** [comment]
Ah I see. Thanks a lot
